name: ELOUD_UHC
version: '1.4.6-SNAPSHOT'
main: me.dalibex.UHC_DBasic.UHC_DBasic
api-version: '1.21'
authors: [ Dalibex ]

commands:
  uhcadmin:
    description: Abre un panel con los ajustes de administración
    usage: /uhcadmin
  uhccommands:
    description: Muestra lista de comandos del Plugin UHC_DBasic
    usage: /uhccommands
  test:
    description: Comando de prueba
    usage: /test
  start:
    description: Inicia el proceso de UHC (crea muro)
    usage: /start [size]
  confirmarstart:
    description: Comando interno para confirmar el inicio de partida (no necesita uso manual)
    usage: Llamado automáticamente por "/start" para confirmación
  cancelarstart:
    description: Comando interno para cancelar el inicio de partida (no necesita uso manual)
    usage: Llamado automáticamente al cancelar la acción de empezar partida
  reset:
    description: Prepara el mundo y lo pone en espera para usar "/start"
    usage: /reset
  nequipo:
    description: Crea o renombra a tu equipo, sea de 1, 2, 3 o 4 jugadores
    usage: /nequipo [nombre
  tpartes:
    description: Ajusta el tiempo manualmente
    usage: /tpartes
  lang:
    description: Cambia el idioma
    usage: /lang [idioma]